### ISSUE TITLE
Couldn't create new branch

### ISSUE THREAD

**Issue by nikit-cpp** [sheimi/SGit#155]
Can you add this feature?
As in desktop client:
git checkout -b mynewbranch
Or
git branch mynewbranch
git checkout mynewbranch

**Comment by liscju** [comment]
@nikit-cpp  In dev branch this functionality is already implemented, but i have no idea when it will be merged to master and when it will be released with new version

**Comment by ChoiZ** [comment]
:+1:

**Comment by phcoder** [comment]
Should be fixed in https://github.com/phcoder/SGit, published on https://play.google.com/store/apps/details?id=ch.phcoder.jigit. Note: I made a fork only because my pull requests went unanswered. I'm welcoming any merge back into SGit.

**Comment by liscju** [comment]
@phcoder great idea as long as original repo will seems abandoned as now. My only complain is that you are making commits to the master branch which in some ways duplicates functionalities already implemented in dev branch. For example (creating new branch): 

https://github.com/phcoder/SGit/commit/0d6f1179d063345baed99e6f5624c1171a60fb7d

duplicates this:

https://github.com/sheimi/SGit/commit/2e3bd6bde2fdb6ca05cbb0527f9255e6d62e2d77

This will make complicated merging those branches. As far as you gonna make such things right i am interested in sending patches to your fork(as long as original project repo will be dead as now). Cheers

**Comment by phcoder** [comment]
Thank you for pointing me to dev branch. I'm looking into manually merging it into mine. It's it OK with you?

**Comment by liscju** [comment]
In my view you shouldn't just merge your branch with dev because those(your master and sgit dev) have some functionalities in commits in common. 

To start with clean state of development in your repo you probably should start with sgit dev branch(which has newest version of source code of sgit) and merge it(rebase to maintain linear commit history?) with new version of your master that doesn't contain commits that duplicate already implemented functionalities in dev. If you just merge your master with dev you gonna have a mess from start. 

Reviewing the difference might be tedious and boring but in my view that's the only proper way , especially taking into consideration the fact that Sgit maitainer maybe gonna get back to work on project and it will be reasonable to merge new stuff in fork to orig. Good luck

**Comment by phcoder** [comment]
Commits you mentioned actually aren't duplicates but complimentary functionality, namely git checkout -b branch and git checkout -b branch commit. So I keep both of them. I almost finished rebasing and will push shortly

**Comment by liscju** [comment]
Ok, could be - i did only a quick glance and wrote my reflections:P

**Comment by phcoder** [comment]
I rebased my fork in dev and force-pushed it. You're welcome to send me pull requests. I'll publish new version in about a week time.

**Comment by phcoder** [comment]
(Publish on play store I mean)

**Comment by liscju** [comment]
Good job, thanks for letting me know.

**Comment by schumaml** [comment]
Isn't this available in the current version?

**Comment by liscju** [comment]
@schumaml in master my commit fixing this is merged, so i guess issue could be closed (i guess because i didnt test current version of sgit)

**Comment by maks** [comment]
Yes, this seems to work fine for me with the current release (v1.3.1) of SGit
