### ISSUE TITLE
font size too large in editor windows

### ISSUE THREAD

**Issue by flyisland** [sheimi/SGit#161]
When I tried to edit my .md file, the font size will become too large and the line will not wrap correctly.

View Mode:
![view mode](http://flyisland.github.io/IssueImages/SGit/161/view.jpg)

Edit Mode:
![Edit Mode](http://flyisland.github.io/IssueImages/SGit/161/editor.jpg)

Android Version: 4.2.2
![OS](http://flyisland.github.io/IssueImages/SGit/161/android.jpg)

**Comment by teresaejunior** [comment]
This is happening to me too on MIUI 7.1.3, it seems the font is set to **300px** in the file *SGit/assets/css/codemirror.css*:

```
.CodeMirror {
  /* Set height, width, borders, and global font properties here */
  font-family: monospace;
  height: 300px;
}
```

**Comment by teresaejunior** [comment]
This has been fixed in the latest sGit from the Play Store (not yet on F-Droid).

**Comment by maks** [comment]
@teresaejunior Thansk for checking and reporting its fixed for you now.
I'm not sure why it hasn't updated in f-droid, it may be because I incremented the versionCode but not the versionName for the latest release and the build was broken previously for that versionName (but not versionCode). Anyways, F-droid builds are outside of my control, but it should sort itself out once 1.3.4 goes out shortly.

**Comment by teresaejunior** [comment]
Yes, sGit was not the only application I have noticed to be out of date on F-Droid.

BTW I'm glad to see sGit is being given some attention again!
