### ISSUE TITLE
Starts cloning, shows progress, but then finishes without anything there.

### ISSUE THREAD

**Issue by johann-petrak** [sheimi/SGit#169]
Just installed SGit on a Samsung Note Pro 12.2 (Model SM-P900) with Android 4.4.2.
I have tried to install (rather large) git repositories using SSH (the private key is not password protected) and https with userid and password and both cases, the cloning seems to start, SGit shows progress but then the entry disappears from the list and nothing has been cloned. 
None of my repositories can be cloned, I made several attempts for each. No error message is shown in the window.

**Comment by Lrs121** [comment]
I have noticed this occurs with large(ish) repos. I have a few theories as to why it happens but i havent confirmed any of them yet. Cloning smaller reops doesnt seem to cause the issue. it may not be possible to clone large repos at this time.

**Comment by FabianInostroza** [comment]
I just today noticed this problem too, at the end, the following message is shown: "attempt to use Inflater after calling end".

**Comment by Lrs121** [comment]
Thats what i remember. though i have no idea what that means

**Comment by maks** [comment]
Large repos are likely causing out of memory issues due to the limited heap size available to apps, especially on a 4.4 devices as max heap size is in general lower on earlier versions of Android.
It would be very helpful if someone on this thread could post a URL for a public repo where they see this error occurring so I can  confirm this is the root cause.

**Comment by Lrs121** [comment]
I don't remember which repo was specifically causing me problems but I believe the git for the Linux kernel might cause it. I'll take a look around in the morning for one that will definitely cause it and link it here.

**Comment by maks** [comment]
@Lrs121 yikes, the kernel repo would definitely do it.
The memory usage is due to the need to inflate objects inside pack files, which are "deflated" using zlib (see: https://www.kernel.org/pub/software/scm/git/docs/technical/pack-format.txt and https://codewords.recurse.com/issues/three/unpacking-git-packfiles).

 Jgit (the git library that SGit app uses) has a "streaming" mode that should allow it to cope with large compressed objects in packfiles, up to a point - I'll check how that paramter is set in the current SGit release...
This has been quite well documented in the egit bugtracker (egit being the original client for the jgit library):
https://bugs.eclipse.org/bugs/show_bug.cgi?id=394078

**Comment by Lrs121** [comment]
With understanding how that works I believe the stream gets overloaded with the current setup, for one reason or another. I do know that android has a flag for large memory allocations, I don't remember if that's used currently. If it is not, perhaps if that is used in conjunction with the streaming mode will help handle slightly larger repos. It probably wouldn't be able to hand the kernel repo, but it may give other repos a fighting chance of succeeding. 

Another option maybe to include a clone depth setting that allows users to only pull a specific number of recent commits. Much like clone-depth=1. I don't know if Jgit has that implemented. If it does it may help with some overhead.

**Comment by maks** [comment]
The comment https://github.com/sheimi/SGit/issues/65#issuecomment-73890069 from #65 is worth looking into as Agit of cocurse also uses jgit.

**Comment by Maurdekye** [comment]
After looking into this problem and coming upon this issue thread, I'm confused because it seems to be happening with my repo as well, even though it's only about 7.7mb. I don't think that could be considered a large repo. I'm currently running rooted kitkat 5.1 on an LG G4.

**Comment by maks** [comment]
@Maurdekye If you have a public repo that is consistently showing this behaviour, that would be a big help in debugging and testing the possible fix.

**Comment by maks** [comment]
This issue was moved to maks/MGit#54
