### ISSUE TITLE
Button names does not match actions

### ISSUE THREAD

**Issue by Tratoschek** [sheimi/SGit#183]
The string on the menu buttons are wrong. I have German locale, so don't know whether this is the reason.

The following happens:

- Go to repo
- Type to menu button
- Type Pull -> Action for "Creating new branch" is called
- Type Push -> Action for "Pulling" is executed.

etc.

I have version 1.3.0 (from F-Droid).

**Comment by moorchegue** [comment]
Same here. 1.3.0, Chinese locale.

**Comment by VivianePons** [comment]
Same in French

**Comment by maks** [comment]
Thank you all for the reports.
Unfortunately I missed that a number o the translations were missing a newly added menu item and that caused all of these to be misaligned.
Its been fixed as of commit ab40c4572f809e4874662c17e12371f8a27d2ccd

I'll get this out in a new release to Google Play asap.

I've also added a number of other translations that were missing in commit: b1eaa4a6f74406cf18d1b282c81189f59d5159ed
It be really help if any native speakers could review those changes and suggest any corrections, a I was only able to get the translations mechanically via Google translate. Either Pull Requests or just new issue wuth any required corrections would be great.

**Comment by andy-maier** [comment]
I saw that some of the german strings need translation or improvement. I'll provide details later (when I have a real screen in front of me, working from phone right now).

**Comment by andy-maier** [comment]
The things I saw in the commits mentioned above had already been fixed in commit 57a0a13, and I'm happy with the result. @trendfisher: great work!

**Comment by moorchegue** [comment]
This probably doesn't belong here, but… is it hard to make a language switch in the settings somewhere, not just tie it to a device locale?

Idea under this is that things like `git` make much more sense in English anyway, and translations (esp. non-human ones, and esp. when bugs like this appear) could be confusing. 

When you mess with a repo you need to know percisely what you're doing, and fuzzy translations are not helping.

Command line interfaces for instance are never tranlated. You don't type ``git 拉取``，you type `git pull` and that makes perfect sense to everybody in the world.

Thoughts?

**Comment by andy-maier** [comment]
Some of the german translations simply use the english word, or add it in parenthesis. That is one way to deal with it.

If the proposed language setting was available, i would imnediately set the language to english.

**Comment by trendfischer** [comment]
I had the same problem identifying the git commands. That is why I added some of the command line terms into the german translation in parenthesis.

I would support, that using the automated translation, is no good idea (but I deeply appreciate the intention and the work to add translations like this). The problem seems to be, that automated translations have some problems with the context. Even with a few years experience with GIT now, I had to thought a few moments on how to translate some messages.

I would prefer new translations in english. On translating the new messages, I had to open the english original to get the meaning of some the automated translations. But since I use SGit, I am willing to help, if new translations are needed.

**Comment by maks** [comment]
@trendfischer yes I agree, automated translations are not very useful - I am thinking of reverting them. 
Do others agree with @moorchegue about preferring no translations at all?

The only reason I used them was that the translations were already existing and only missing a small number of items that had apparently been added since the original translations had been done.

As I mentioned it would be great if native speakers of the existing translations: French, Hebrew, Japanese and Chinese (simplified) could contribute better translations than the ones I've added.

**Comment by maks** [comment]
Thanks everyone for your help and feedback.

I've built a new release candidate with the translation menu item fix and published it in an open beta on Google Play. If anyone is able to test it out prior to it being published that would be great. You can opt-in to the beta at this url:
https://play.google.com/apps/testing/me.sheimi.sgit

I am also tagging all releases that go out to Play, using Githubs releases featues, so this latest one is available at: https://github.com/sheimi/SGit/releases/tag/v1.3.1-rc1

If there are no issues reported I'd like to get this out to the production release on Play tomorrow night (GMT+10) as I think having the menu items mis-ordered is a very serious and potentially very harmful bug for users of SGit.

**Comment by trendfischer** [comment]
I've checked the version and the translations works, at least in german. Only on showing the progress, I do not get the german translation. I tested "pull" and did not got "Führe 'pull' durch", instead I got a simple "pull". But I do not mind. The button names are matching the actions now, and that is important.

**Comment by maks** [comment]
@trendfischer thanks again for testing. I've moved this into production, so the update should start going out via Play in a few hours time.
