### ISSUE TITLE
Add ability to do a git fetch -p to cleanup old deleted branches

### ISSUE THREAD

**Issue by scofflan** [sheimi/SGit#229]
Currently I have a few repos whcih get a lot of WIP branches that get deleted on the origin but remain locally on sgit. Adding the functionality to do a fetch pull would help to keep the branch list clean.

**Comment by maks** [comment]
If I understand correctly, you'd like to have SGit automatically remove local refs to refs on remotes that have been deleted?

**Comment by scofflan** [comment]
I'm not sure doing this automatically would be the way to go. That could be problematic. However having an option to select "fetch and prune" would be very helpful for people following repos with many temporary remote branches. 

The man entry has the following for git fetch -p

-p, --prune
           After fetching, remove any remote-tracking references that no longer exist on
           the remote. Tags are not subject to pruning if they are fetched only because of
           the default tag auto-following or due to a --tags option. However, if tags are
           fetched due to an explicit refspec (either on the command line or in the remote
           configuration, for example if the remote was cloned with the --mirror option),
           then they are also subject to pruning.

Thanks, I love SGit,
Sam

**Comment by maks** [comment]
Thanks Sam, yes that is what I meant, I should have just copy/pasted the manual entry as you did rather than trying to re-phrase it.
This sound like a very useful feature, I've put it into the first milestone that I think I can reasonably get it into. In regards to UI, I think it will go into the fetch dialog as an option, though I'm open to other suggestions as I'm not convinced that's necessarily the best way to implement this.

**Comment by maks** [comment]
This issue was moved to maks/MGit#35
