### ISSUE TITLE
still cant select sd card as storage

### ISSUE THREAD

**Issue by 21h** [sheimi/SGit#233]
Only internal memory available. show /storage directory in dir select dialog. Or much much better way is an individual directory for each repo.

**Comment by Lrs121** [comment]
This is may or may not be by design. Android versions greater than 4.4 have write protections on the sdcard. So if you were able to select the sdcard cloning, pulling, etc. on a git repo would be lost to the black void as android would prevent writing to the card.

The only exception, I think, is if you were to select the apps folder under the /sdcard/android/data/me.sheimi.sgit/ folder. Much like how the app originally functioned when new git repos were cloned. They were stored under /storage/android/data/me.sheimi.sgit/

**Comment by maks** [comment]
@21h I think this is due to an issue with the implementation of Android on your device. The file browser that is used now to set the root directory for repos starts at the location in the filesystem returned by getExternalStorageDirectory() [as per here](https://github.com/sheimi/SGit/blob/master/src/main/java/me/sheimi/sgit/activities/explorer/ExploreRootDirActivity.java#L23)

which should be the location in the file system where your external storage is mounted.

Because I reused the existing "explorer" functionality already in SGit there is no ".." in the directory listings, so I will need to add that in, to enable you to navigate up to your filesystem root and then onto whereever your device is mounting your external storage. I think this wil be generally useful as on some devices, user may also wish to use USB storage which again would likely be mounted somewhere else in the filesystem.

The alternative which I don't want to do is to use the root of the local filesystem (aka "/") as the starting point for the directory chooser as this could unnecessarily confuse other users.

**Comment by 21h** [comment]
Android 5.1. Of course rooted. Confuse git users?) Git users not blonde, they are very hard to confuse )

**Comment by maks** [comment]
No, but there is also no reason to not follow Android conventions without a good reason and the path returned by getExternalStorageDirectory() is the correct root directory for user files stored in "external" storage and "shared", thus read/writable by the current user.

**Comment by cgogolin** [comment]
I have the same problem on two Samsung devices. getExternalStorageDirectory() here points to /storage/emulated/0/ and my internal memory is just not big enough to hold the repository I would like to work on.

**Comment by maks** [comment]
@cgogolin this is definitely something that I'll get implemented soon, BUT please be aware if you are planning to use SGit to work on very large repos, there are other known issues that are likely to cause you problems.

**Comment by m1cm1c** [comment]
@maks In case you mean the 4 GiB problem on 32 bit platforms: I told to guys from the git mailing list about that a while ago and they were quick with fixing it. It's fixed for almost 2 months now and definitely is in the releases by now (I checked a few weeks ago).

**Comment by Lrs121** [comment]
@m1cm1c i think that isn't the issue @maks is referring to.
I believe he is referring to issue #169 where there is an issue with the streaming method jgit uses.

**Comment by 21h** [comment]
Cloning repo, entering Remote url and Local Path, program writes to me "Repository name cant contain slash". Best way: allow user store repo anywhere. Individually for every repo own store path.

**Comment by m1cm1c** [comment]
> forget about write protections on sd card. git users rooting their phones as fast as possible.

Apps don't need root access to write the SD card. However, with Marshmallow a system in which apps need to be granted permission to do certain things (access the microphone, access the camera, access the SD card, access the contacts, request the device's location, access the phone, etc.) was introduced. Just like in earlier versions of Android, you're shown the permissions the app wants when you install an app but now additionally you (as a user) have to go to the settings and turn the permissions that app might need on or wait until the app tries to use one of them. If the app tries to do something it hasn't been granted permission to do, the user is asked via an overlay to grant that one specific app one specific permission. (Much like when an app first tries to use root access.)

So no root access required. **← TL;DR**

**Comment by jkufner** [comment]
I've got hit by this issue too. It would be really nice if file browser could go up from default SD card location.

The file browser could provide a way to enter path manually and then navigate from there. Such feature would require only a button in the toolbar and a text prompt. Also it would allow a user to copy the currently selected path.

**Comment by maks** [comment]
Given how many people are affected by this, I've changed this to be a bug, given it top priority and re-scheduled it for the current release.
