### ISSUE TITLE
no way to see log info

### ISSUE THREAD

**Issue by JeremyHH** [sheimi/SGit#42]
When I make a pull request on a given repository, I encounter a "pull failed" error but without additional info I can't know what to do.

**Comment by d10** [comment]
Can we get details about your Android version and the repository you were cloning?

**Comment by l00g33k** [comment]
I have a similar problem where only a toast message flashing "Pull failed" for a couple of seconds and then nothing else happened. I am not sure if it is actually the same "Updating references" step error.

However, I found the solution to my problem and this is the first hit Googling "sgit failed to pull" so I thought I'll post my solution in case other may find it helpful.

Turned out the problem is the missing tracking branch specification.

In order to pull, the local branch must have had a tracking branch specified (https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches). To see if a tracking branch is specified for the branch you wanted to pull (using the git from TerminalIDE, another great tool for Android):

    $ git branch -avv
    master             3ac1ab3 initial
    tw                 d22671f [remotes/sgit/tw] f624 nexus
    remotes/sgit/tw    d22671f f624 nexus

If you don't see square brackets then you are missing the tracking branch. For example, master branch does not have a tracking branch. You can add it as follow:

    git checkout tw
    git branch --set-upstream sgit/tw

The pull will succeed.

**Comment by l00g33k** [comment]
I have a similar problem where only a toast message flashing "Pull failed" for a couple of seconds and then nothing else happened. I am not sure if it is actually the same "Updating references" step error.

However, I found the solution to my problem and this is the first hit Googling "sgit failed to pull" so I thought I'll post my solution in case other may find it helpful.

Turned out the problem is the missing tracking branch specification.

In order to pull, the local branch must have had a tracking branch specified (https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches). To see if a tracking branch is specified for the branch you wanted to pull (using the git from TerminalIDE, another great tool for Android):

    $ git branch -avv
    master             3ac1ab3 initial
    tw                 d22671f [tw700/tw] f624 nexus
    remotes/tw700/tw   d22671f f624 nexus

If you don't see square brackets then you are missing the tracking branch. For example, master branch does not have a tracking branch. You can add it as follow:

    git branch --set-upstream tw tw700/tw

The pull will succeed.

**Comment by maks** [comment]
This issue was moved to maks/MGit#67
